[2025-05-19T08:44:49.282+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_taxi_pipeline.load_data manual__2025-05-19T08:43:58.742681+00:00 [queued]>
[2025-05-19T08:44:49.296+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_taxi_pipeline.load_data manual__2025-05-19T08:43:58.742681+00:00 [queued]>
[2025-05-19T08:44:49.297+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-19T08:44:49.316+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_data> on 2025-05-19 08:43:58.742681+00:00
[2025-05-19T08:44:49.322+0000] {standard_task_runner.py:60} INFO - Started process 209 to run task
[2025-05-19T08:44:49.326+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'nyc_taxi_pipeline', 'load_data', 'manual__2025-05-19T08:43:58.742681+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/nyc_taxi_pipeline.py', '--cfg-path', '/tmp/tmpu4_lhtu1']
[2025-05-19T08:44:49.329+0000] {standard_task_runner.py:88} INFO - Job 35: Subtask load_data
[2025-05-19T08:44:49.353+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-19T08:44:49.397+0000] {task_command.py:423} INFO - Running <TaskInstance: nyc_taxi_pipeline.load_data manual__2025-05-19T08:43:58.742681+00:00 [running]> on host dc3ebaf2dadb
[2025-05-19T08:44:49.703+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nyc_taxi_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T08:43:58.742681+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-19T08:43:58.742681+00:00'
[2025-05-19T08:44:49.705+0000] {nyc_taxi_pipeline.py:50} INFO - Starting data loading...
[2025-05-19T08:46:28.214+0000] {local_task_job_runner.py:234} INFO - Task exited with return code -9
[2025-05-19T08:46:28.515+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
