[2025-05-19T10:07:58.248+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_taxi_pipeline.load_data manual__2025-05-19T10:06:55.822672+00:00 [queued]>
[2025-05-19T10:07:58.262+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_taxi_pipeline.load_data manual__2025-05-19T10:06:55.822672+00:00 [queued]>
[2025-05-19T10:07:58.263+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-19T10:07:58.291+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_data> on 2025-05-19 10:06:55.822672+00:00
[2025-05-19T10:07:58.299+0000] {standard_task_runner.py:60} INFO - Started process 209 to run task
[2025-05-19T10:07:58.304+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'nyc_taxi_pipeline', 'load_data', 'manual__2025-05-19T10:06:55.822672+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/nyc_taxi_pipeline.py', '--cfg-path', '/tmp/tmpisuoo0zo']
[2025-05-19T10:07:58.308+0000] {standard_task_runner.py:88} INFO - Job 60: Subtask load_data
[2025-05-19T10:07:58.334+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-19T10:07:58.386+0000] {task_command.py:423} INFO - Running <TaskInstance: nyc_taxi_pipeline.load_data manual__2025-05-19T10:06:55.822672+00:00 [running]> on host 9bb4a58ab096
[2025-05-19T10:07:58.784+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nyc_taxi_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T10:06:55.822672+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-19T10:06:55.822672+00:00'
[2025-05-19T10:07:58.786+0000] {nyc_taxi_pipeline.py:50} INFO - Starting data loading...
[2025-05-19T10:15:31.990+0000] {load.py:67} INFO - Uploaded chunk 30
[2025-05-19T10:15:31.991+0000] {load.py:69} INFO - Data successfully loaded into table 'nyc_taxi_data'
[2025-05-19T10:15:31.992+0000] {nyc_taxi_pipeline.py:69} INFO - Data successfully loaded
[2025-05-19T10:15:31.993+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-19T10:15:32.007+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=nyc_taxi_pipeline, task_id=load_data, execution_date=20250519T100655, start_date=20250519T100758, end_date=20250519T101532
[2025-05-19T10:15:32.078+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-19T10:15:32.104+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
